-- ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ --
-- ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ --
-- ■■■■■■       ■■■■■■■            ■■■■       ■■■■■■■■■■ --
-- ■■■■■■  ■■   ■■■■■■■   ■■■■■■■  ■■■■  ■■   ■■■■■■■■■■ --
-- ■■■■■■  ■■   ■■■■■■■   ■■       ■■■■  ■■   ■■■■■■■■■■ --
-- ■■■■■■  ■■      ■■■■   ■■■■   ■■■■■■  ■■       ■■■■■■ --
-- ■■■■■■  ■■■■■   ■■■■   ■■     ■■■■■■  ■■■■■■   ■■■■■■ --
-- ■■■■■■  ■■■■■   ■■■■   ■■   ■■■■■■■■  ■■■■■■   ■■■■■■ --
-- ■■■■■■          ■■■■        ■■■■■■■■           ■■■■■■ --
-- ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ --
-- ■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■ --
-- Auteur : Eluecque Anthony, Fournier Benjamin, Dournel Frédéric

-- TUPLES POUR LA TABLE CHAMPIONS LEAGUE OF LEGENDS LFL 2022 --
--  Source  : https://champsdb.gg/

INSERT INTO CHAMPIONS(nom_champion,id_role_1,id_role_2) VALUES
('Aatrox',5,NULL),
('Ahri',4,NULL),
('Akali',5,4),
('Akshan',4,NULL),
('Alistar',3,NULL),
('Amumu',1,3),
('Anivia',4,NULL),
('Annie',4,NULL),
('Aphelios',4,2),
('Ashe',2,3),
('Aurelion Sol',4,NULL),
('Azir',4,NULL),
('Bard',3,NULL),
('Bel Veth',1,NULL),
('Blitzcrank',1,3),
('Brand',3,NULL),
('Braum',3,NULL),
('Caitlyn',2,NULL),
('Camille',5,NULL),
('Cassiopeia',4,NULL),
('Cho Gath',5,NULL),
('Corki',4,NULL),
('Darius',5,NULL),
('Diana',1,NULL),
('Dr.Mundo',5,NULL),
('Draven',2,NULL),
('Ekko',1,4),
('Elise',1,NULL),
('Evelynn',1,NULL),
('Ezreal',2,NULL),
('Fiddlesticks',1,NULL),
('Fiora',5,NULL),
('Fizz',4,NULL),
('Galio',4,NULL),
('Gangplank',5,NULL),
('Garen',5,NULL),
('Gnar',5,NULL),
('Gragas',5,NULL),
('Graves',1,NULL),
('Gwen',5,NULL),
('Hecarim',1,NULL),
('Heimerdinger',4,3),
('Illaoi',5,NULL),
('Irelia',5,4),
('Ivern',1,NULL),
('Janna',3,NULL),
('Jarvan IV',1,NULL),
('Jax',5,NULL),
('Jayce',5,NULL),
('Jhin',2,NULL),
('Jinx',2,NULL),
('K Sante',5,NULL),
('Kai Sa',2,NULL),
('Kalista',2,NULL),
('Karma',3,NULL),
('Karthus',1,NULL),
('Kassadin',4,NULL),
('Katarina',4,NULL),
('Kayle',5,NULL),
('Kayn',1,NULL),
('Kennen',5,NULL),
('Kha Zix',1,NULL),
('Kindred',1,NULL),
('Kled',5,NULL),
('Kog Maw',2,NULL),
('LeBlanc',4,NULL),
('Lee Sin',1,NULL),
('Leona',3,NULL),
('Lillia',1,NULL),
('Lissandra',4,NULL),
('Lucian',2,NULL),
('Lulu',3,NULL),
('Lux',4,3),
('Malphite',5,NULL),
('Malzahar',4,NULL),
('Maokai',5,1),
('Master YI',1,NULL),
('Miss Fortune',2,NULL),
('Mordekaiser',5,NULL),
('Morgana',3,NULL),
('Nami',3,NULL),
('Nasus',5,NULL),
('Nautilus',3,NULL),
('Neeko',4,NULL),
('Nidalee',1,NULL),
('Nilah',2,NULL),
('Nocturne',1,NULL),
('Nunu & Willump',1,NULL),
('Olaf',5,NULL),
('Orianna',4,NULL),
('Ornn',5,NULL),
('Pantheon',1,3),
('Poppy',1,NULL),
('Pyke',3,NULL),
('Qiyana',4,NULL),
('Quinn',5,NULL),
('Rakan',3,NULL),
('Rammus',1,NULL),
('Rek Sai',1,NULL),
('Rell',3,NULL),
('Renata Glasc',3,NULL),
('Renekton',5,NULL),
('Rengar',1,NULL),
('Riven',5,NULL),
('Rumble',5,NULL),
('Ryze',4,NULL),
('Samira',2,NULL),
('Sejuani',5,1),
('Senna',3,NULL),
('Seraphine',3,NULL),
('Sett',5,NULL),
('Shaco',1,NULL),
('Shen',5,NULL),
('Shyvana',1,NULL),
('Singed',5,NULL),
('Sion',5,NULL),
('Sivir',2,NULL),
('Skarner',1,NULL),
('Sona',3,NULL),
('Soraka',3,NULL),
('Swain',4,3),
('Sylas',4,NULL),
('Syndra',4,NULL),
('Tahm Kench',5,NULL),
('Taliyah',1,4),
('Talon',1,4),
('Taric',3,NULL),
('Teemo',5,NULL),
('Tresh',3,NULL),
('Tristana',2,NULL),
('Trundle',1,NULL),
('Tryndamere',5,NULL),
('Twisted Fate',4,NULL),
('Twitch',2,NULL),
('Udyr',1,NULL),
('Urgot',5,NULL),
('Varus',4,2),
('Vayne',5,2),
('Veigar',4,NULL),
('Vel Koz',3,NULL),
('Vex',4,NULL),
('Vi',1,NULL),
('Viego',1,NULL),
('Viktor',4,NULL),
('Vladimir',4,NULL),
('Volibear',5,1),
('Warwik',1,NULL),
('Wukong',1,NULL),
('Xayah',2,NULL),
('Xerath',4,3),
('Xin Zhao',1,NULL),
('Yasuo',5,4),
('Yone',5,4),
('Yorick',5,NULL),
('Yuumi',3,NULL),
('Zac',1,NULL),
('Zed',1,4),
('Zeri',2,NULL),
('Ziggs',4,NULL),
('Zilean',3,NULL),
('Zoe',4,NULL),
('Zyra',3,NULL);



